-- wallet-service needs its own outbox: money moved in this database must become a
-- fact other services can observe, and the row that moved the money and the row
-- announcing it have to commit together or not at all.
--
-- This is a deliberate copy of auth-server's table, not a shared module. The two
-- services own separate databases with separate lifecycles; a shared migration would
-- couple their deploys and make one service's rollback silently alter another's
-- schema.

CREATE TABLE outbox_events (
    -- This id IS the eventId in the published envelope, and therefore the single
    -- identity a consumer dedups on. Generated once, never reused.
    id               UUID           PRIMARY KEY,
    -- Which service produced this. Not used for routing -- everything from
    -- wallet-service goes to one topic -- but recorded so a row is traceable back
    -- to its producer.
    aggregate_type   VARCHAR(50)    NOT NULL,
    -- The aggregate this is about: the transfer id. Also the Kafka message key,
    -- which pins every event for one transfer to a single partition and therefore
    -- to a single consumer at a time, in order.
    aggregate_id     UUID           NOT NULL,
    event_type       VARCHAR(100)   NOT NULL,
    schema_version   INTEGER        NOT NULL DEFAULT 1,
    -- Captured from the inbound request's X-Correlation-Id at write time. NOT
    -- generated by the relay: an id minted at publish time would identify nothing,
    -- because it would not link back to the request that caused the transfer.
    correlation_id   UUID           NOT NULL,
    payload          JSONB          NOT NULL,
    occurred_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    -- NULL means "not yet published". The relay scans for exactly this.
    published_at     TIMESTAMPTZ,
    -- Retry counter. Exists so a permanently poison message has somewhere to go
    -- once a dead-letter policy exists.
    attempts         INTEGER        NOT NULL DEFAULT 0,
    last_error       VARCHAR(512)
);

-- The relay's scan. Partial, because it only ever asks for unpublished rows, and
-- most of the table is published history.
CREATE INDEX idx_outbox_unpublished ON outbox_events (occurred_at)
    WHERE published_at IS NULL;
