server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      probes:
        enabled: true