-- auth-server schema. Owned exclusively by Flyway.
--
-- authdb holds identity only: credentials, roles, and the outbox. It never holds
-- wallet or ledger data. The link to wallet-service is the user id, which becomes
-- the JWT "sub" claim and, downstream, wallet-service's customers.owner_id.

CREATE TABLE users (
    id            UUID           PRIMARY KEY,
    username      VARCHAR(64)    NOT NULL UNIQUE,
    email         VARCHAR(255)   NOT NULL,
    -- Placeholder until the login slice. BCrypt/argon2 hash, never plaintext and
    -- never a reversible encoding.
    password_hash VARCHAR(255)   NOT NULL,
    roles         VARCHAR(255)   NOT NULL DEFAULT 'USER',
    enabled       BOOLEAN        NOT NULL DEFAULT true,
    -- Bumped to revoke every token ever issued to this user: the JWT carries the
    -- value it had at issue time and each request compares it against this column.
    token_version INTEGER        NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- Login is case-insensitive, so uniqueness and lookup must both fold case.
-- A plain UNIQUE on username would allow "Ada" and "ada" as separate accounts,
-- which is a support ticket and a security question ("is this the same person?").
CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username));

-- The transactional outbox. One row per event the auth-server intends to publish,
-- committed in the same transaction as the business row that justifies it.
--
-- The payload is JSONB rather than a typed table because the envelope shape is
-- this service's own contract, and consumers must never query this table. Storing
-- it as JSONB also means adding an event type needs no migration here.
CREATE TABLE outbox_events (
    -- This id IS the eventId in the published envelope. It is the single identity
    -- a consumer dedups on, so it must be generated once and never reused.
    id               UUID           PRIMARY KEY,
    -- Which service owns the event. Not used for routing (all auth events go to
    -- one topic); recorded so a row is traceable back to its producer.
    aggregate_type   VARCHAR(50)    NOT NULL,
    -- The user this event is about. Doubles as the Kafka message key, which is
    -- what pins every event for one aggregate to a single partition and therefore
    -- to a single consumer at a time.
    aggregate_id     UUID           NOT NULL,
    event_type       VARCHAR(100)   NOT NULL,
    schema_version   INTEGER        NOT NULL DEFAULT 1,
    -- Captured from the inbound request's X-Correlation-Id at write time, NOT
    -- generated by the relay. A value minted at publish time would identify
    -- nothing: it would not link back to the request that caused the event.
    correlation_id   UUID           NOT NULL,
    payload          JSONB          NOT NULL,
    occurred_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    -- NULL means "not yet published". The relay scans for exactly this.
    published_at     TIMESTAMPTZ,
    -- Retry counter. Exists so a permanently poison message has somewhere to go
    -- once a dead-letter policy exists.
    attempts         INTEGER        NOT NULL DEFAULT 0,
    last_error       VARCHAR(512)
);

-- The relay's hot query: unpublished rows, oldest first. A partial index keeps
-- this proportional to the backlog rather than to the total history, which grows
-- forever and is never deleted.
CREATE INDEX idx_outbox_unpublished ON outbox_events (occurred_at)
    WHERE published_at IS NULL;

-- Safety net for the relay: if it dies between "Kafka accepted the message" and
-- "we recorded published_at", the row is still NULL and will be re-sent. That is
-- the expected path, not a bug -- it is exactly why consumers must be idempotent.
CREATE INDEX idx_outbox_unpublished_aggregate ON outbox_events (aggregate_id)
    WHERE published_at IS NULL;