server:
  port: 8083

spring:
  application:
    name: bank-mock

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true